stages:
- stage: Stage1
  jobs: 
  - deployment: DeployPPE
    environment: ganes-test-env
    pool: 'Azure pipelines'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'